name: Build and Push Containers
on:
  push:
    branches:
      - temp-build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker build and push REST
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/smpte/st2138-b:rest
          build-args: |
            TAG=status-update-REST
            VERSION=rest
      
      - name: Docker build and push gRPC
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/smpte/st2138-b:grpc
          build-args: |
            TAG=status-update-gRPC
            VERSION=grpc